version: 2.1

jobs:
  test:
    docker:
      - image: cimg/node:23.0.0
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Run tests
          command: npm run test
      - run:
          name: Create database folder
          command: mkdir -p tmp && touch tmp/db.sqlite3
      - run:
          name: Run Migrations
          command: node ace migration:run
workflows:
  test-deploy:
    jobs:
      - test